#ifndef IPGEOLOCATION_CERT
#define IPGEOLOCATION_CERT

const char ipgelocation_cert[] = 
    "-----BEGIN CERTIFICATE-----\n"
    "MIIFQjCCBOegAwIBAgIQAsT0uD0vOh4k0M8+O4qiVDAKBggqhkjOPQQDAjBKMQsw\n"
    "CQYDVQQGEwJVUzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEgMB4GA1UEAxMX\n"
    "Q2xvdWRmbGFyZSBJbmMgRUNDIENBLTMwHhcNMjIwNTI4MDAwMDAwWhcNMjMwNTI4\n"
    "MjM1OTU5WjB1MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQG\n"
    "A1UEBxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEe\n"
    "MBwGA1UEAxMVc25pLmNsb3VkZmxhcmVzc2wuY29tMFkwEwYHKoZIzj0CAQYIKoZI\n"
    "zj0DAQcDQgAEy9qT/G3kdERHj5dHAvd6XtV21hJmewl7g7orfpBDKMdKmCpfGUoQ\n"
    "NWeK2A83NEmEti5vax1EDXuACjxkJfWqNqOCA4IwggN+MB8GA1UdIwQYMBaAFKXO\n"
    "N+rrsHUOlGeItEX62SQQh5YfMB0GA1UdDgQWBBQAADMLHdClXXVll5NxKzZCXO8g\n"
    "bTBGBgNVHREEPzA9ghVzbmkuY2xvdWRmbGFyZXNzbC5jb22CEiouaXBnZW9sb2Nh\n"
    "dGlvbi5pb4IQaXBnZW9sb2NhdGlvbi5pbzAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0l\n"
    "BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMHsGA1UdHwR0MHIwN6A1oDOGMWh0dHA6\n"
    "Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9DbG91ZGZsYXJlSW5jRUNDQ0EtMy5jcmwwN6A1\n"
    "oDOGMWh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9DbG91ZGZsYXJlSW5jRUNDQ0Et\n"
    "My5jcmwwPgYDVR0gBDcwNTAzBgZngQwBAgIwKTAnBggrBgEFBQcCARYbaHR0cDov\n"
    "L3d3dy5kaWdpY2VydC5jb20vQ1BTMHYGCCsGAQUFBwEBBGowaDAkBggrBgEFBQcw\n"
    "AYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEAGCCsGAQUFBzAChjRodHRwOi8v\n"
    "Y2FjZXJ0cy5kaWdpY2VydC5jb20vQ2xvdWRmbGFyZUluY0VDQ0NBLTMuY3J0MAwG\n"
    "A1UdEwEB/wQCMAAwggGABgorBgEEAdZ5AgQCBIIBcASCAWwBagB3AOg+0No+9QY1\n"
    "MudXKLyJa8kD08vREWvs62nhd31tBr1uAAABgQhLI3IAAAQDAEgwRgIhAOOJ/yj0\n"
    "TDqMW6bGYBVgj/JDPSnI4V5C+NlGy+urv1jfAiEAzazEuYXTs1YgB+qTvmTnPZ9w\n"
    "icC8zAa0C34nlbvdc9sAdgA1zxkbv7FsV78PrUxtQsu7ticgJlHqP+Eq76gDwzvW\n"
    "TAAAAYEISyN/AAAEAwBHMEUCIG1qsg/v+zHLDyyHnKBtNvzQThDMA083eZdOVGCj\n"
    "4xIOAiEA4MBBJYUbHiDPq6BNYbz33enuh+WSBE08Kzi4EqjjYnYAdwCzc3cH4YRQ\n"
    "+GOG1gWp3BEJSnktsWcMC4fc8AMOeTalmgAAAYEISyOxAAAEAwBIMEYCIQC3w5vy\n"
    "E3UuDIALGj4EUxgE/OHxJXd67Kz1zYLVPyVgSwIhAOkFqBUSW28N4LL86QEaH8Rs\n"
    "aNn2gXB3jIqE3FyUVAh5MAoGCCqGSM49BAMCA0kAMEYCIQDJKxL9JICdQ2FH9GYH\n"
    "G7evQ8yuZtbm5V9yGVEhNVIjMgIhAPH37Cb+T6GEEldDRvc2O0aJKv5qmOTndjUA\n"
    "Qn0JBebf\n"
    "-----END CERTIFICATE-----\n";

#endif